### PR TITLE
Dockercompose

### PR DESCRIPTION
**Pull request by jetpacktuxedo**
Probably should have some tests associated with this but #yolo or something

### CODE REVIEW

**Comment by jetpacktuxedo** [comment]
Tests fail because you got rid of the requirements file and I pulled that in from your other branch :P

**Comment by jetpacktuxedo** [comment]
Fixed that, now it is failing because I changed how we handle secrets.yml in order to make it more docker-friendly. I'm not really sure where travis is pulling that stuff from though.

**Comment by bhanderson** [comment]
Is there docs how to run it?

**Comment by jetpacktuxedo** [comment]
`docker-compose build` will build it, `docker-compose up` will bring it online

`docker compose up --build` should do both at once iirc.

Container should grab :5000 when it comes up.

That should probably be in the readme or something though.

You'll also need to take your secrets.yml and put it in `~/.config/.pbnh.yml`

**Comment by bhanderson** [comment]
There isn't a docker compose file to build?

**Comment by jetpacktuxedo** [comment]
... did I not `git add` that?

😂🔫👌

**Comment by jetpacktuxedo** [comment]
All my tests pass locally so I am pretty sure the `secrets.yml` is the only reason this is still failing... lemme try something else

**Comment by jetpacktuxedo** [comment]
ayyyyyy :point_right: :sunglasses: :point_right: 

I figured it out

**Comment by jetpacktuxedo** [comment]
Just found another bug with this... for some reason about.md never gets rendered.

Tracking it down now.

**Comment by bhanderson** [comment]
Cool

**Comment by jetpacktuxedo** [comment]
fixed

**Pull request merged**
